AWSTemplateFormatVersion: '2010-09-09'
Description: Portfolio services.
Parameters:
  FrontendBucketName:
    Description: Bucket to store artifacts for the public frontend
    Type: String
  DomainName:
    Description: Root domain name used to host both frontend and backend
    Type: String
  DomainHostedZoneId:
    Description: Hosted zone id of domain used to communicate to the CloudFront
    Type: String
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
      - DomainName: !Ref DomainName
        HostedZoneId: !Ref DomainHostedZoneId
      ValidationMethod: DNS
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FrontendBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Portfolio"
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
        - Action: s3:GetObject
          Effect: Allow
          Resource: !Sub "${FrontendBucket.Arn}/*"
          Principal:
            AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}"
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: FrontendBucket
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref DomainName
        CustomErrorResponses:
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        DefaultCacheBehavior:
          TargetOriginId: BucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
          - GET
          - HEAD
          CachedMethods:
          - GET
          - HEAD
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            Headers: []
            QueryString: false
            QueryStringCacheKeys: []
            Cookies:
              Forward: none
          MaxTTL: 31536000
          MinTTL: 0
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
        - DomainName: !Sub "${FrontendBucketName}.s3.amazonaws.com"
          Id: BucketOrigin
          S3OriginConfig:
            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only
  FrontendDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DomainHostedZoneId
      Name: !Ref DomainName
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2
      Type: A
Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket
    Export:
      Name: "PortfolioFrontendBucketName"
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Export:
      Name: "PortfolioCloudFrontDistributionId"