name: Deploy Frontend

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    
    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Create local directories
      run: |
        mkdir -p .local/deploy
    
    - name: Install dependencies
      working-directory: ./
      run: npm ci
    
    - name: Deploy frontend
      run: pwsh ./deploy/deploy-frontend.ps1
